name: Update Dalamud Repositories and Plugins

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup File Structure
        run: |
          # Create directory structure for Dalamud repositories and plugins
          mkdir -p repositories
          mkdir -p plugins/core
          mkdir -p plugins/partners
          mkdir -p plugins/affiliated
          echo "Initialized directories for Dalamud plugins and repository JSONs."

      - name: Fetch JSON Files for Repositories
        run: |
          # Download repository JSON files
          curl -o repositories/ment.json https://love.puni.sh/ment.json
          curl -o repositories/kawaii.json https://puni.sh/api/repository/kawaii
          curl -o repositories/taurenkey.json https://puni.sh/api/repository/taurenkey
          curl -o repositories/nightmarexiv.json https://github.com/NightmareXIV/MyDalamudPlugins/raw/main/pluginmaster.json
          curl -o repositories/veyn.json https://puni.sh/api/repository/veyn
          curl -o repositories/croizat.json https://puni.sh/api/repository/croizat
          curl -o repositories/det.json https://puni.sh/api/repository/det
          curl -o repositories/ice.json https://puni.sh/api/repository/ice
          curl -o repositories/jukka.json https://puni.sh/api/repository/jukka
          curl -o repositories/sourpuh.json https://puni.sh/api/repository/sourpuh
          curl -o repositories/carvel_li.json https://plugins.carvel.li/
          curl -o repositories/herc.json https://puni.sh/api/repository/herc
          echo "Fetched all repository JSON files."

      - name: Generate pluginmaster.json
        run: |
          # Generate pluginmaster.json file dynamically
          cat <<EOF > pluginmaster.json
{
  "Plugins": [
    { "Name": "Artisan", "Description": "Crafting solver, automated lists, and macros", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "AutoHook", "Description": "Automated fishing & solving", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "AutoRetainer", "Description": "Retainer & submersible automation", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "Avarice", "Description": "Positional assistant with feedback", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "LazyLoot", "Description": "Looting automation", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "Orbwalker", "Description": "Slidecasting helper", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "Pandora's Box", "Description": "Quality of life focused tweaks", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "Saucy", "Description": "MGP & Triple Triad automation", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "Splatoon", "Description": "Fight mechanic helper", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "YesAlready", "Description": "Dynamic dialogue box and bothers automation", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "Wrath Combo", "Description": "Combo plugin, with auto-rotation and optimization", "Repository": "https://love.puni.sh/ment.json" },
    { "Name": "Explorer's Icebox", "Description": "Island Sanctuary Leveling/Gathering Buddy", "Repository": "https://puni.sh/api/repository/ice" },
    { "Name": "Hoard Farm", "Description": "For the Hoard-achievement farmer", "Repository": "https://puni.sh/api/repository/jukka" },
    { "Name": "NecroLens", "Description": "DeepDungeon ESP", "Repository": "https://puni.sh/api/repository/jukka" },
    { "Name": "Autoduty", "Description": "Automates dungeon and trial duty management", "Repository": "https://puni.sh/api/repository/herc" }
  ]
}
EOF
          echo "Generated pluginmaster.json dynamically."

      - name: Reset and Push Updates
        run: |
          git fetch origin main
          git reset --hard origin/main
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add repositories/ plugins/ pluginmaster.json
          git commit -m "Auto-update repository JSONs, plugin files, and pluginmaster.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
