name: Update Dalamud Repositories and Plugins

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup File Structure
        run: |
          # Create directory structure for Dalamud repositories and plugins
          mkdir -p repositories
          mkdir -p plugins/core
          mkdir -p plugins/partners
          mkdir -p plugins/affiliated
          echo "Initialized directories for Dalamud plugins and repository JSONs."

      - name: Fetch JSON Files for Repositories
        run: |
          # Download repository JSON files
          curl -o repositories/ment.json https://love.puni.sh/ment.json
          curl -o repositories/kawaii.json https://puni.sh/api/repository/kawaii
          curl -o repositories/taurenkey.json https://puni.sh/api/repository/taurenkey
          curl -o repositories/nightmarexiv.json https://github.com/NightmareXIV/MyDalamudPlugins/raw/main/pluginmaster.json
          curl -o repositories/veyn.json https://puni.sh/api/repository/veyn
          curl -o repositories/croizat.json https://puni.sh/api/repository/croizat
          curl -o repositories/det.json https://puni.sh/api/repository/det
          curl -o repositories/ice.json https://puni.sh/api/repository/ice
          curl -o repositories/jukka.json https://puni.sh/api/repository/jukka
          curl -o repositories/sourpuh.json https://puni.sh/api/repository/sourpuh
          curl -o repositories/carvel_li.json https://plugins.carvel.li/
          curl -o repositories/herc.json https://puni.sh/api/repository/herc
          echo "Fetched all repository JSON files."

      - name: Organize Plugin Data (Optional)
        run: |
          # Placeholder to organize or copy specific plugins into subdirectories if needed.
          echo "Organize plugin files here if needed."

      - name: Commit and Push Updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add repositories/ plugins/
          git commit -m "Auto-update repository JSONs and plugin files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
